### ISSUE TITLE
Documentation for creating `server.pem`

### ISSUE THREAD

**Issue by hyena** [mutgos/mutgos_server#29]
Should include instructions on how to make it with `openssl` as well as `certbot`, where to put it, and caution the user on the importance of protecting it.

**Comment by hyena** [comment]
Also the description should support the usage case of a separate cert and key file since that's the standard output from certbot and openssl

**Comment by zelerin** [comment]
Is this something you are already working on or is it open for anyone?

**Comment by hyena** [comment]
It doesn't have to be me, but I am likely the best one to do it.

**Comment by zelerin** [comment]
If you want to do it, let me know and I'll assign it. :)

While reviewing the pull request for SSL, I noticed you're checking in a certificate.  Other projects have gotten in trouble for checking in default certificates because they end up being used in production by users who don't understand the significance, and this becomes a huge security risk.

This issue will be used to delete that certificate file once good directions and/or a script is provided.  In other words, this issue isn't closed until there is good documentation and/or scripts, AND the sample certificate file is deleted.  For initial testing right now, providing the sample is fine.

**Comment by hyena** [comment]
That's a really good point: If we enable a lazy end-user to do something harmful/insecure they probably will. Our approach with weasyl was to generate the self-signed files ourselves in the typical developer setup (see: https://github.com/Weasyl/weasyl/blob/26dea3a51da6bde8627b9240dc5e584cfe013257/Vagrantfile#L65) and we can probably do something similar here: Definitely in the Dockerfile, possibly in the Makefile.

Regarding assigning it to me, on a volunteer project I prefer to only take on tickets when I'm either ready to work on them or consider myself the only one with the sufficient state to work on them easily. Neither applies here, but you can go ahead and assign this to me if it makes things better for bookkeeping. I don't mind doing this and I want it to be done; I'm just not ready to start it.

**Comment by hyena** [comment]
n.b. As part of this change, `.gitignore` should be updated to help prevent a user from checking in anything accidentally. *.pem, *.crt at minimum.

**Comment by zelerin** [comment]
I'll leave it unassigned until you are ready.  Just email or whatnot when ready and I'll assign.  I am going to try and use assign when the person knows they are going to work it and they intend to work on it in the near-ish future.

**Comment by hyena** [comment]
Assign this to me now.

**Comment by zelerin** [comment]
Fixed by #38
